# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: emitos
  pool: 5
  username: root #emitos
  password: #defaultpw #emit0s
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: emitos
  pool: 5
  username: root #emitos
  password: #defaultpw #emit0s
  host: localhost