# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: emitos
  pool: 5
<<<<<<< HEAD
  username: root
  password: #defaultpw
=======
  username: root #emitos
  password: #emit0s
>>>>>>> 871f74fdf6a6963250a63ab9ac1d948f64e2e963
  host: localhost

